server:
  port: 9090

spring:
  data:
    redis:
      password: xxx
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/yoyo.db
    username: root
    password: xxx
  jpa:
    hibernate:
      # 每次启动更改数据表结构
      ddl-auto: update
    # 显示数据库操作记录
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

influxdb:
  url: http://127.0.0.1:8086
  token: xxx
  bucket: equipments
  org: xdu

kafka:
  topic:
    topic1: yoyo-add-data
    topic2: yoyo-set-cache
